// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-UeDWKJuMaDPQvLltZAsuaKVp5nrP8lI',
    appId: '1:1037409689954:web:716c305fb066d4ace84c3b',
    messagingSenderId: '1037409689954',
    projectId: 'techwiz-b81be',
    authDomain: 'techwiz-b81be.firebaseapp.com',
    storageBucket: 'techwiz-b81be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRj8yLw1CUsoUcec0fsJt0imiU78R1qK4',
    appId: '1:1037409689954:android:93f1e244b32c0dbae84c3b',
    messagingSenderId: '1037409689954',
    projectId: 'techwiz-b81be',
    storageBucket: 'techwiz-b81be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdsy6ex9Ue1LpEq195e4lIVHepZWnIwLg',
    appId: '1:1037409689954:ios:d14d3b23ac406e10e84c3b',
    messagingSenderId: '1037409689954',
    projectId: 'techwiz-b81be',
    storageBucket: 'techwiz-b81be.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
